
import React from 'react';
import { AlertTriangle } from 'lucide-react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-12 sm:py-16 md:py-20 relative overflow-hidden">
      {/* Background effects */}
      <div className="absolute bottom-0 left-0 right-0 h-1/2 bg-gradient-to-t from-neon-magenta/5 to-transparent"></div>
      
      <div className="section-container">
        <div className="max-w-4xl mx-auto glass-panel p-4 sm:p-6 md:p-8 rounded-xl border border-white/10">
          <div className="flex items-center gap-3 mb-4">
            <AlertTriangle className="h-5 w-5 sm:h-6 sm:w-6 text-neon-yellow" />
            <h2 className="text-xl sm:text-2xl md:text-3xl font-bold text-white">Legal Disclaimer</h2>
          </div>
          
          <div className="space-y-3 sm:space-y-4 text-sm sm:text-base text-muted-foreground">
            <p className="text-neon-cyan font-medium">
              SIMULATION NOTICE: Celebrity Chatline GPT is an AI SIMULATION powered by GPT-4o technology. All conversations are artificially generated and are NOT authentic interactions with real celebrities.
            </p>
            
            <p>
              Celebrity Chatline GPT is an AI entertainment service that uses advanced language models to simulate text conversations with celebrity personalities. These simulations are based on public information and are not affiliated with, endorsed by, or connected to the actual individuals being portrayed.
            </p>
            
            <p>
              All interactions are generated by artificial intelligence and do not represent the actual thoughts, opinions, or words of the real celebrities. The AI may not always be accurate and may sometimes generate content that is fictional or speculative in nature.
            </p>
            
            <p>
              This service is intended for entertainment purposes only. Users should not rely on any information provided by the AI for making important decisions, and should verify any factual claims independently. AI Web Tools LLC does not guarantee the accuracy, completeness, or usefulness of any information provided through this service.
            </p>
            
            <p>
              By using Celebrity Chatline GPT, you acknowledge that you understand the AI-generated nature of these interactions and agree to use the service responsibly. AI Web Tools LLC reserves the right to moderate content and may refuse service to anyone using the platform inappropriately.
            </p>
            
            <p>
              All trademarks, character names, and celebrity identities are the property of their respective owners. This service makes no claim to these intellectual properties and acknowledges that the simulated conversations are transformative, creative works distinct from the actual personalities being referenced.
            </p>
            
            <p>
              For questions regarding this disclaimer or the service, please contact <a href="mailto:contact@ai-webtools.com" className="text-neon-cyan hover:underline">contact@ai-webtools.com</a>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
